version: '3'
services:
  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: $PROJECT_NAME
      POSTGRES_USER: $PROJECT_DB_USER
      POSTGRES_PASSWORD: $PROJECT_DB_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file: .env
  cache:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  app:
    build:
      context: .
    env_file: .env
    volumes:
      - '.:/app'
    ports:
      - '80:80'
    links:
      - db
      - cache
    depends_on:
      - db
      - cache
    # entrypoint: ./api.py
volumes:
  postgres: null
  gem_cache: null
